name: Test Scoring App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        if [ -f Pipfile ]; then pipenv install -d; fi
    - name: Unit tests with unittest
      run: |
        pipenv run coverage run -m unittest -v
        pipenv run coverage xml -o coverage.xml
#    - name: Check if coverage under 100
#      run: |
#        coverage report --fail-under=100
